apiVersion: v1
kind: Secret
metadata:
  name: boto3-secrets
  namespace: default
  labels:
    app: sqs-scaler-job
type: Opaque
stringData:
  SQS_QUEUE_URL: "<SQS_QUEUE_URL>"
  S3_BUCKET_NAME: "<S3_BUCKET_NAME>"
  AWS_REGION: "<AWS_REGION>"
  AWS_ACCESS_KEY_ID: "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
  AWS_SECRET_ACCESS_KEY: "XXXXXXXXXXXXXXXXXXXXXXXXX"